### ISSUE TITLE
Question on training I-JEPA baseline with ViT-B encoder

### ISSUE THREAD

**Issue by vimalthilak** [amirbar/StoP#2]
Hey @amirbar ,

Congratulations on your paper. Excellent work!

Did the numbers presented in the paper for the baseline use the same config that was used for StoP [included here]?(https://github.com/amirbar/StoP/blob/main/configs/pretrain/vit-b16.yaml)

I have been playing around with I-JEPA official code but having issues reproducing the numbers in that paper. I am wondering if I may need to enable augmentations to match numbers for ViT-B/16 and ViT-L/16 models

**Comment by amirbar** [comment]
Hi @vimalthilak,

> Did the numbers presented in the paper for the baseline use the same config that was used for StoP [included here]?(https://github.com/amirbar/StoP/blob/main/configs/pretrain/vit-b16.yaml)

In Figure 1, Table 1, Table 2, Table 3, Table 4 we either copy the numbers from the I-JEPA paper or run evaluation using the I-JEPA official pre-trained checkpoints (either publicly or internally released within Meta).

In Table 5, Table 6, Figure 4, Table 7 and Table 8 we pretrain everything from scratch.

> I have been playing around with I-JEPA official code but having issues reproducing the numbers in that paper. 

It may be better to directly open an issue in I-JEPA repository (i'm not an author on the paper).

> I am wondering if I may need to enable augmentations to match numbers for ViT-B/16 and ViT-L/16 models

In my experience, it will be helpful to enable these augmentations. I discuss the differences between the code bases here: [https://github.com/amirbar/StoP?tab=readme-ov-file#differences-compared-to-the-official-i-jepa-implementation](url).

**Comment by vimalthilak** [comment]
Hey @amirbar thanks for the fast response. Really appreciate the time you spent answering my question. I will close this issue out as there are no outstanding questions.

> It may be better to directly open an issue in I-JEPA repository (i'm not an author on the paper).

This repo was archived so I can no longer open an issue there but no big deal. I will need to do a careful read of the paper and appendix to figure what I am missing to get my configs aligned with the implementation. This is what I meant by issue in my initial post :).

**Comment by vimalthilak** [comment]
Closing out issue
